# Generated by Django 3.2 on 2023-06-10 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Post Views',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('user_agent', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['ip_address', 'user_agent'], name='content_req_ip_addr_b2dd70_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='request',
            unique_together={('ip_address', 'user_agent')},
        ),
        migrations.AddField(
            model_name='postview',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.post'),
        ),
        migrations.AddField(
            model_name='postview',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.request'),
        ),
        migrations.AlterUniqueTogether(
            name='postview',
            unique_together={('post', 'request')},
        ),
    ]
