# Generated by Django 3.2 on 2023-06-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20230610_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_agent',
            field=models.CharField(max_length=500),
        ),
    ]
