# Generated by Django 4.2.1 on 2023-06-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20230611_0024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Client',
        ),
        migrations.AlterUniqueTogether(
            name='postview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='postview',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postview',
            name='request',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='content_cli_ip_addr_882fe6_idx',
            old_name='content_req_ip_addr_b2dd70_idx',
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.ManyToManyField(blank=True, editable=False, to='content.client'),
        ),
        migrations.DeleteModel(
            name='PostView',
        ),
    ]
