# Generated by Django 3.2 on 2023-06-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20230602_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='notified',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
